apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-golangliuba-yaml
  namespace: argocdliuba
spec:
  project: default
  source: 
    repoURL:  https://github.com/Liubzzz/argo1.git
    targetRevision: main
    path: golang
  destination:
    server: https://kubernetes.default.svc
    namespace: argogolangyaml
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
